local opt = vim.opt

opt.autoindent = true -- Copy indent from current line when starting a new line
-- opt.colorcolumn = "80"
opt.cursorline = true -- Show cursor line
opt.swapfile = false -- Don't use swapfile
opt.expandtab = true -- Use spaces instead of tabs
opt.exrc = true
opt.foldmethod = "expr"
opt.hidden = true
opt.hlsearch = true
opt.ignorecase = true -- Ignore case letters when searching
opt.incsearch = true
opt.laststatus = 2 -- Set global statusline
opt.lazyredraw = true -- Faster scrolling
opt.listchars = 'eol:¬,tab:>·,trail:~,extends:>,precedes:<,space:␣' -- Display whitespace characters
opt.list = true
opt.nu = true
opt.number = true
opt.hlsearch = false
opt.backup = false
opt.foldenable = false
opt.errorbells = false
opt.writebackup = false
opt.relativenumber = true
opt.scrolloff = 2
opt.shiftwidth = 0
opt.showmatch = false -- Highlight matching parenthesis
opt.signcolumn = "yes"
opt.smartcase = true -- Ignore lowercase for entire patterns
opt.smartindent = true -- Autoindent new lines
opt.softtabstop = -1
opt.spell = true
opt.splitbelow = true -- Horizontal split to the bottom
opt.splitright = true -- Vertical split to the right
opt.tabstop = 4 -- 1 tab = 4 spaces
opt.termguicolors = true -- Enable 24-but RGB colours
opt.updatetime = 300 -- ms to wait to trigger an event
opt.wrap = true
